; =====================================================
; Main AutoHotkey Script
; Automatically includes all .ahk files from scripts folder
; =====================================================

#Requires AutoHotkey v2.0
#SingleInstance Force

; Set working directory to script's location
SetWorkingDir A_ScriptDir
Persistent()

; =====================================================
; Dynamic Script Loader
; Automatically includes all .ahk files from the 'scripts' folder
; =====================================================

FileAppend(A_Now " - UpdateIncludes triggered`n", "debug_log.txt")

UpdateIncludes() {
    IncludeFile := "includes.ahk"
    ScriptFolder := "scripts"

    ; Create scripts folder if it doesn't exist
    if !DirExist(ScriptFolder)
        DirCreate(ScriptFolder)

    ; Generate the list of #Include lines
    IncludeContent := "; This file is automatically generated. Do not edit.`n"
    loop files, ScriptFolder "\*.ahk" {
        IncludeContent .= '#Include "' A_LoopFileFullPath '"`n'
    }

    ; Check if the current includes file matches what we just scanned
    CurrentContent := ""
    if FileExist(IncludeFile)
        CurrentContent := FileRead(IncludeFile)

    if (IncludeContent != CurrentContent) {
        try {
            FileObj := FileOpen(IncludeFile, "w")
            FileObj.Write(IncludeContent)
            FileObj.Close()
            Reload() ; Restart the script to apply new includes
        }
    }
}

; Run the auto-loader
UpdateIncludes()

; Include the generated file (must exist)
if !FileExist("includes.ahk")
    FileAppend("; Initial file`n", "includes.ahk")

#Include includes.ahk

; =====================================================
; Global Settings (optional)
; =====================================================

; Escape key to exit the script
; Esc:: ExitApp

; Reload script with Ctrl+R
^r:: Reload

; =====================================================
; Main Script Logic
; =====================================================

; Add any global hotkeys or initialization code here
; Example:
; MsgBox "Main script loaded successfully!"

; Tray icon tooltip
A_IconTip := "My AutoHotkey Scripts"